include(joinpath(@__DIR__, "test_support.jl"))
include(joinpath(@__DIR__, "test_band_input_and_lattice.jl"))
include(joinpath(@__DIR__, "test_band_runtime.jl"))
include(joinpath(@__DIR__, "test_contour.jl"))
include(joinpath(@__DIR__, "test_pair_checks.jl"))
include(joinpath(@__DIR__, "test_projection.jl"))
include(joinpath(@__DIR__, "test_oam.jl"))
include(joinpath(@__DIR__, "test_spin_observables.jl"))
include(joinpath(@__DIR__, "test_wsvec.jl"))
include(joinpath(@__DIR__, "test_supercell.jl"))
include(joinpath(@__DIR__, "test_superham.jl"))
include(joinpath(@__DIR__, "test_band_service.jl"))
include(joinpath(@__DIR__, "flux", "runtests.jl"))
